import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2d3133",
        "watermark-red": "#EF4444",
        "status-observado-text": "#C2410C",
        outline: "#8e706d",
        "on-primary-fixed": "#410003",
        "secondary-container": "#e5e2e1",
        surface: "#f7f9fb",
        "on-tertiary-fixed-variant": "#5a4300",
        "outline-variant": "#e2bebb",
        error: "#ba1a1a",
        "on-background": "#191c1e",
        "surface-bright": "#f7f9fb",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-container": "#656464",
        "on-secondary-fixed": "#1c1b1b",
        "surface-container": "#eceef0",
        "inverse-on-surface": "#eff1f3",
        "tertiary-container": "#6c5200",
        "surface-dim": "#d8dadc",
        "tertiary-fixed": "#ffdf98",
        "status-rechazado-bg": "#FEE2E2",
        "on-secondary-fixed-variant": "#474646",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "primary-container": "#a81b1f",
        "surface-tint": "#b52527",
        "on-surface": "#191c1e",
        "status-pendiente-text": "#B45309",
        "on-surface-variant": "#5a403e",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#f3c54f",
        "status-observado-bg": "#FFEDD5",
        "on-primary-fixed-variant": "#920412",
        "status-pendiente-bg": "#FEF3C7",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary-fixed": "#251a00",
        "inverse-primary": "#ffb3ad",
        "status-aprobado-bg": "#D1FAE5",
        "primary-fixed": "#ffdad6",
        "status-rechazado-text": "#B91C1C",
        "tertiary-fixed-dim": "#eec14b",
        "on-primary-container": "#ffbab4",
        secondary: "#5f5e5e",
        background: "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "primary-fixed-dim": "#ffb3ad",
        "surface-variant": "#e0e3e5",
        "status-aprobado-text": "#047857",
        "surface-container-high": "#e6e8ea",
        "surface-container-lowest": "#ffffff",
        primary: "#83000e",
        "secondary-fixed-dim": "#c8c6c5",
        tertiary: "#503c00",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "32px",
        gutter: "24px",
        unit: "4px",
        xs: "4px",
        lg: "24px",
        md: "16px",
        sm: "8px",
      },
      maxWidth: {
        "container-form": "672px",
        "container-max-form": "672px",
        "container-admin": "1152px",
        "container-max-admin": "1152px",
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-base": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "body-bold": ["15px", { lineHeight: "22px", fontWeight: "600" }],
        "label-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-medium": ["15px", { lineHeight: "22px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
